### ISSUE TITLE
A go back to top button in the header?

### ISSUE THREAD

**Issue by ThisDevDane** [TatriX/odindoc#1]
A button as seen to the right that just takes you back to the top would nice
![image](https://user-images.githubusercontent.com/1834353/146566941-9148b63c-5163-4f63-ac4f-8c7a7f5071e6.png)

**Comment by TatriX** [comment]
You can click on `docs` to get to packages.

**Comment by ThisDevDane** [comment]
Yea okay... that is not clear at all :D So maybe make it clearer that it's clickable?
